export const ROUTE_CONSTANTS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  PROJECT: "/project",
  EMPATTENDANCE: "/EmpAttendance",
  TODAYATTENDANCE: "/TotalAttendance",
  ATTENDANCESHEET: "/AttendanceSheet",
  ALLLEAVEREQUEST: "/AllLeaveRequest",
  APPLYLEAVE: "/ApplyLeave",
  APPLYHISTORY: "/ApplyHistory",
  APPLYPENDING: "/ApplyPending",
  LEAVEBALANCE: "/LeaveBalanace",
  LEAVEAPPLY: "/LeaveApply",
  ADDEMPLOYEE: "/AddEmployee",
  PAYSLIP: "/PaySlip",
  EMPPAYSLIP: "/EmpPayslip",
  ALLEMP: "/AllEmployee",
  SALARYCERTI: "/SalaryCertificate",
  ONBOARD: "/Onboarding",
  LEAVE:"/Leave",
  // APPLYLEAVE:"/ApplyLeave",

};
